# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobID', models.PositiveIntegerField(blank=True, default=0)),
                ('Name', models.CharField(blank=True, default='CSearch', max_length=50)),
                ('CurrentStep', models.PositiveIntegerField(blank=True, default=0)),
                ('Failed', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2017, 12, 19, 14, 48, 56, 919318), verbose_name='date created')),
                ('UploadedFile', models.FilePathField(blank=True, default='')),
                ('UploadedFileType', models.CharField(choices=[('xyz', 'xyz'), ('pdb', 'pdb')], default='xyz', max_length=10)),
                ('CSearchType', models.CharField(choices=[('Random', 'Random'), ('ExplicitSolvent', 'ExplicitSolvent'), ('DFT', 'DFT')], default='Random', max_length=30)),
                ('Note', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
