# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='FailedReason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 14, 56, 28, 119295), verbose_name='date created'),
        ),
    ]
