# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0002_auto_20171219_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 17, 19, 9, 453430), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='UploadedFile',
            field=models.FileField(blank=True, default='', upload_to=b''),
        ),
    ]
