# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 23:29
from __future__ import unicode_literals

import csearch.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0003_auto_20171219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 18, 29, 13, 459615), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='UploadedFile',
            field=models.FileField(upload_to=csearch.models.user_directory_path),
        ),
    ]
