# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0004_auto_20171219_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 18, 40, 18, 267631), verbose_name='date created'),
        ),
    ]
