# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 23:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0005_auto_20171219_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Failed',
            new_name='Successful',
        ),
        migrations.AlterField(
            model_name='job',
            name='CSearchType',
            field=models.CharField(choices=[('Random', 'Random'), ('ExplicitSolvent', 'ExplicitSolvent'), ('DFT', 'DFT')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 18, 47, 57, 779894), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='UploadedFileType',
            field=models.CharField(choices=[('xyz', 'xyz'), ('pdb', 'pdb')], default='', max_length=10),
        ),
    ]
