# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-20 21:27
from __future__ import unicode_literals

import csearch.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0006_auto_20171219_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobID', models.PositiveIntegerField(blank=True, default=0)),
                ('Name', models.CharField(blank=True, default='CSearch', max_length=50)),
                ('CurrentStep', models.PositiveIntegerField(blank=True, default=0)),
                ('Successful', models.BooleanField(default=False)),
                ('FailedReason', models.CharField(blank=True, default='', max_length=100)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2017, 12, 20, 16, 27, 22, 675762), verbose_name='date created')),
                ('UploadedFile', models.FileField(upload_to=csearch.models.user_directory_path)),
                ('UploadedFileType', models.CharField(choices=[('xyz', 'xyz'), ('pdb', 'pdb')], default='', max_length=10)),
                ('CSearchType', models.CharField(choices=[('Random', 'Random'), ('ExplicitSolvent', 'ExplicitSolvent'), ('DFT', 'DFT')], default='', max_length=30)),
                ('Note', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
