# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-20 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0007_auto_20171220_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 16, 31, 6, 352959), verbose_name='date created'),
        ),
    ]
