# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-20 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0008_auto_20171220_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 17, 1, 10, 192213), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='CurrentStep',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
