# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-21 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0009_auto_20171220_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CSearchType',
            field=models.CharField(choices=[('Random', 'Random'), ('Replica', 'Replica'), ('DFT', 'DFT')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 14, 35, 25, 691112), verbose_name='date created'),
        ),
    ]
