# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-21 20:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0010_auto_20171221_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='csearchjob',
            name='RandomEPS',
            field=models.FloatField(blank=True, default=0.01),
        ),
        migrations.AddField(
            model_name='csearchjob',
            name='RandomForcefield',
            field=models.CharField(choices=[('UFF', 'UFF'), ('GAFF', 'GAFF'), ('Ghemical', 'Ghemical'), ('MMFF94', 'MMFF94'), ('MMFF94s', 'MMFF94s')], default='UFF', max_length=30),
        ),
        migrations.AddField(
            model_name='csearchjob',
            name='RandomNMinSamples',
            field=models.PositiveIntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='csearchjob',
            name='RandomNRotamers',
            field=models.PositiveIntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='csearchjob',
            name='RandomNSteps',
            field=models.PositiveIntegerField(blank=True, default=2500),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='CSearchType',
            field=models.CharField(choices=[('Random', 'Random'), ('Replica', 'Replica'), ('DFT', 'DFT')], default='Random', max_length=30),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 22, 46, 52261), verbose_name='date created'),
        ),
    ]
