# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-21 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0011_auto_20171221_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 26, 5, 289721), verbose_name='date created'),
        ),
    ]
