# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-11 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0013_auto_20171221_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='csearchjob',
            name='CurrentStatus',
            field=models.CharField(choices=[('0', 'to be start'), ('1', 'running'), ('2', 'finished'), ('3', 'something wrong')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 16, 44, 44, 461421), verbose_name='date created'),
        ),
    ]
