# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0017_auto_20180130_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 11, 28, 14, 312255), verbose_name='date created'),
        ),
    ]
