# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 17:13
from __future__ import unicode_literals

import csearch.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0020_auto_20180130_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='csearchjob',
            name='SmilesStr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 12, 13, 22, 918284), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='UploadedFile',
            field=models.FileField(blank=True, upload_to=csearch.models.user_directory_path),
        ),
    ]
