# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-01 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0022_auto_20180201_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 15, 53, 57, 691283), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='SmilesStr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
