# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csearch', '0023_auto_20180201_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csearchjob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 15, 53, 4, 147489), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='csearchjob',
            name='UploadedFileType',
            field=models.CharField(choices=[('xyz', 'xyz'), ('pdb', 'pdb'), ('sdf', 'sdf'), ('mol2', 'mol2')], default='', max_length=10),
        ),
    ]
