# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-14 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phreeqcdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 12, 25, 36, 501107), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='GFWforElement',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
