# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-14 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phreeqcdb', '0002_auto_20180214_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reaction', models.CharField(blank=True, default='', max_length=100)),
                ('LogK', models.FloatField(blank=True, default=0.0)),
                ('DeltaH', models.FloatField(blank=True, default=0.0)),
                ('DeltaHUnits', models.CharField(choices=[('kJ/mol', 'kJ'), ('kcal/mol', 'kcal'), ('J/mol', 'J'), ('cal/mol', 'cal')], default='kJ/mol', max_length=10)),
                ('AEA1', models.FloatField(blank=True, default=0.0, help_text='Analytical A1')),
                ('AEA2', models.FloatField(blank=True, default=0.0)),
                ('AEA3', models.FloatField(blank=True, default=0.0)),
                ('AEA4', models.FloatField(blank=True, default=0.0)),
                ('AEA5', models.FloatField(blank=True, default=0.0)),
                ('GammaA', models.FloatField(blank=True, default=0.0)),
                ('GammaB', models.FloatField(blank=True, default=0.0)),
                ('NoCheck', models.BooleanField(default=False)),
                ('MoleBalance', models.CharField(default='', max_length=50)),
                ('Note', models.CharField(blank=True, default='', max_length=200)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 14, 17, 14, 0, 3411), verbose_name='date created')),
                ('Ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phreeqcdb.Refs')),
            ],
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 17, 14, 0, 2132), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='GFWforElement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='GFWorFormula',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
    ]
