# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-15 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phreeqcdb', '0004_auto_20180215_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMasterSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExchangeName', models.CharField(blank=True, default='', max_length=20)),
                ('ExchangeMaster', models.CharField(blank=True, default='', max_length=20)),
                ('Note', models.CharField(blank=True, default='', max_length=200)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 324081), verbose_name='date created')),
                ('Ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phreeqcdb.Refs')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reaction', models.CharField(blank=True, default='', max_length=100)),
                ('LogK', models.FloatField(blank=True, default=0.0)),
                ('DeltaH', models.FloatField(blank=True, default=0.0)),
                ('DeltaHUnits', models.CharField(choices=[('kJ/mol', 'kJ'), ('kcal/mol', 'kcal'), ('J/mol', 'J'), ('cal/mol', 'cal')], default='kJ/mol', max_length=10)),
                ('GammaA', models.FloatField(blank=True, default=0.0)),
                ('GammaB', models.FloatField(blank=True, default=0.0)),
                ('Davies', models.BooleanField(default=False)),
                ('Note', models.CharField(blank=True, default='', max_length=200)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 325300), verbose_name='date created')),
                ('Ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phreeqcdb.Refs')),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=20)),
                ('BasicStatement', models.CharField(blank=True, default='', max_length=500)),
                ('Note', models.CharField(blank=True, default='', max_length=200)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 326357), verbose_name='date created')),
                ('Ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phreeqcdb.Refs')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceMasterSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BindingSite', models.CharField(blank=True, default='', max_length=20)),
                ('SurfaceMaster', models.CharField(blank=True, default='', max_length=20)),
                ('Note', models.CharField(blank=True, default='', max_length=200)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 322285), verbose_name='date created')),
                ('Ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phreeqcdb.Refs')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reaction', models.CharField(blank=True, default='', max_length=100)),
                ('LogK', models.FloatField(blank=True, default=0.0)),
                ('Note', models.CharField(blank=True, default='', max_length=200)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 323176), verbose_name='date created')),
                ('Ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phreeqcdb.Refs')),
            ],
        ),
        migrations.AlterField(
            model_name='phases',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 321178), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 318340), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 48, 39, 319801), verbose_name='date created'),
        ),
    ]
