# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-15 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phreeqcdb', '0005_auto_20180215_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 714998), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='exchangespecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 716227), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='phases',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 712115), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='BasicStatement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rates',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 717236), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='Note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 709270), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 710757), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='surfacemasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 713181), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='surfacespecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 8, 21, 714098), verbose_name='date created'),
        ),
    ]
