# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-15 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phreeqcdb', '0006_auto_20180215_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 362983), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='exchangespecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 364313), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='phases',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 359988), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 365323), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 357033), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 358629), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='surfacemasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 361061), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='surfacespecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 17, 44, 57, 362079), verbose_name='date created'),
        ),
    ]
