# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-16 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phreeqcdb', '0007_auto_20180215_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 708808), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='exchangespecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 710054), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='exchangespecies',
            name='Reaction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='phases',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 705960), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='phases',
            name='PhaseName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='phases',
            name='Reaction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rates',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 711058), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionmasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 703129), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 704581), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='solutionspecies',
            name='Reaction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='surfacemasterspecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 707025), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='surfacespecies',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 12, 12, 16, 707910), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='surfacespecies',
            name='Reaction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
