# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-12 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HgSpeciJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobID', models.PositiveIntegerField(blank=True, default=0)),
                ('Name', models.CharField(blank=True, default='HgSpeci', max_length=50)),
                ('CurrentStep', models.CharField(blank=True, default='0', max_length=10)),
                ('CurrentStatus', models.CharField(choices=[('0', 'to be start'), ('1', 'running'), ('2', 'finished'), ('3', 'something wrong')], default='0', max_length=10)),
                ('Successful', models.BooleanField(default=False)),
                ('FailedReason', models.CharField(blank=True, default='', max_length=100)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2018, 2, 12, 14, 8, 32, 977411), verbose_name='date created')),
                ('SPUnit', models.CharField(choices=[('ppm', 'ppm'), ('ppd', 'ppd')], default='ppm', max_length=10)),
                ('SPTemperature', models.FloatField(default=25.0)),
                ('SPpHMin', models.FloatField(default=0.0)),
                ('SPpHMax', models.FloatField(default=14.0)),
                ('SPpHIncrease', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='SPElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Element', models.CharField(blank=True, default='', max_length=50)),
                ('Concentration', models.FloatField(default=0.0)),
                ('PE', models.BooleanField(default=False)),
                ('PPB', models.BooleanField(default=False)),
                ('PPBFormula', models.CharField(blank=True, default='', max_length=50)),
                ('JobID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hgspeci.HgSpeciJob')),
            ],
        ),
    ]
