# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-12 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgspeci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelements',
            name='ForeignID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hgspeci.HgSpeciJob'),
        ),
        migrations.AlterField(
            model_name='hgspecijob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 16, 21, 52, 633625), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='spelements',
            name='Concentration',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='spelements',
            name='JobID',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
