# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-12 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgspeci', '0002_auto_20180212_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spelements',
            old_name='ForeignID',
            new_name='SPJobID',
        ),
        migrations.AlterField(
            model_name='hgspecijob',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 16, 32, 24, 798087), verbose_name='date created'),
        ),
    ]
