# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PubChemID', models.PositiveIntegerField(default=0)),
                ('Formula', models.CharField(default='-', max_length=30)),
                ('InChIKey', models.CharField(default='-', max_length=50)),
                ('SMILES', models.CharField(default='-', max_length=100)),
                ('IPUACName', models.CharField(default='-', max_length=200)),
                ('Name', models.CharField(default='-', max_length=200)),
                ('Charge', models.SmallIntegerField(default=0)),
                ('MolecularWeight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('CASRegNumber', models.CharField(default='-', max_length=30)),
                ('Source', models.CharField(default='-', max_length=100)),
                ('Note', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dGsolv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dGsolv', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('MolID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expdata.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='PKA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
                ('L', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
                ('IonicStrength', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Electrolyte', models.CharField(choices=[('-', '-'), ('NaCl', 'NaCl'), ('NaClO4', 'NaClO4'), ('NaNO3', 'NaNO3'), ('NH4Cl', 'NH4Cl'), ('KCl', 'KCl'), ('KNO3', 'KNO3'), ('HNa, Cl', 'HNa, Cl')], default='-', max_length=30)),
                ('TemperatureC', models.SmallIntegerField(default=0)),
                ('pKa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dHr', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dSr', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dGr', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('MolID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expdata.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='Refs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefID', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Reference', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StabilityConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metal', models.CharField(choices=[('Hg1+', 'Hg1+'), ('Hg2+', 'Hg2+'), ('Co1+', 'Co1+'), ('Co2+', 'Co2+')], default='Hg2+', max_length=30)),
                ('Constant', models.CharField(choices=[('B', 'B'), ('K', 'K')], default='B', max_length=10)),
                ('M', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
                ('L', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
                ('H', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0)),
                ('OH', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0)),
                ('Lprime', models.CharField(blank=True, choices=[('', ''), ('Cl-', 'Cl-'), ('Br-', 'Br-')], default='', max_length=10)),
                ('LprimeNumber', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0)),
                ('Reactants', models.CharField(default='-', max_length=50)),
                ('IonicStrength', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Electrolyte', models.CharField(choices=[('-', '-'), ('NaCl', 'NaCl'), ('NaClO4', 'NaClO4'), ('NaNO3', 'NaNO3'), ('NH4Cl', 'NH4Cl'), ('KCl', 'KCl'), ('KNO3', 'KNO3'), ('HNa, Cl', 'HNa, Cl')], default='-', max_length=30)),
                ('TemperatureC', models.SmallIntegerField(default=0)),
                ('LogBorK', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dHr', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dSr', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dGr', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('MolID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expdata.Compound')),
                ('ThermalReference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Refs')),
            ],
        ),
        migrations.AddField(
            model_name='pka',
            name='ThermalReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Refs'),
        ),
        migrations.AddField(
            model_name='pka',
            name='pKaReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Refs'),
        ),
        migrations.AddField(
            model_name='dgsolv',
            name='dGsolvReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Refs'),
        ),
    ]
