# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='IPUACName',
            new_name='IUPACName',
        ),
    ]
