# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0002_auto_20161107_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='CASRegNumber',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Formula',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='compound',
            name='IUPACName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compound',
            name='InChIKey',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='compound',
            name='MolecularWeight',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compound',
            name='PubChemID',
            field=models.PositiveIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='compound',
            name='SMILES',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
