# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0003_auto_20161109_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='PubChemID',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
