# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0004_auto_20161109_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrolyte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electrolyte', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pka',
            name='Electrolyte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Electrolyte'),
        ),
        migrations.AlterField(
            model_name='pka',
            name='IonicStrength',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='pka',
            name='TemperatureC',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pka',
            name='dGr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pka',
            name='dHr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pka',
            name='dSr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pka',
            name='pKa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
