# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0005_auto_20161109_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgsolv',
            name='dGsolv',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='Electrolyte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Electrolyte'),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='IonicStrength',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='LogBorK',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='Reactants',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='TemperatureC',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='dGr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='dHr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='dSr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
