# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0006_auto_20161109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stabilityconstants',
            name='Electrolyte',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='expdata.Electrolyte'),
        ),
    ]
