# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0008_auto_20161109_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reactants', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='Reactants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expdata.Reactants'),
        ),
    ]
