# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdata', '0009_auto_20161109_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pka',
            name='IonicStrength',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stabilityconstants',
            name='IonicStrength',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
